# Generated by Django 2.0.9 on 2019-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190908_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
