# Generated by Django 2.0.9 on 2019-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190908_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dl_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(default=''),
        ),
    ]
